### ISSUE TITLE
Support nested values in the course.yml

### ISSUE THREAD

**Issue by ejether** [reactiveops/autohelm#2]
Only support for command line `--set` is available and that complicated deeply nested options and keys that have "." in them.

**Comment by alexander-alvarez** [comment]
Just got burned by this when moving over a file I was manually applying with `helm install` into our `course.yml`

One gets the following error:
`Error: failed parsing --set data: key " <dictionary value>" has no value`

when using a configuration like so
```
values:
    option:
        enabled: <dictionary value>
```
and it has to be flattened manually to

```
values:
    option.enabled: <dictionary value>
```

Ideally the formats should be compatible.

**Comment by ejether** [comment]
@alexander-alvarez  have a look at the `files:`  key in the `course.yml`
It might be helpful.

**Comment by ejether** [comment]
@alexander-alvarez  new version supports nested `values`
