### ISSUE TITLE
Difference to helmfile

### ISSUE THREAD

**Issue by tonyfahrion** [reactiveops/autohelm#21]
Hi,

do you know https://github.com/roboll/helmfile? At least your project looks very similar to helmfile; except that helmfile is more of a wrapper around helm itself.

Just in case you missed it 🙂 

Kind regards

**Comment by ejether** [comment]
Thanks for pointing that ou @tonyfahrion 
We are aware of https://github.com/roboll/helmfile.
`autohelm` is intended to be a wrapper around helm that adds, what we see as, missing features.

One feature that sets `autohelm` apart from other helm wrappers is the ability to pull from an arbitrary path/branch/commit in a git repository. It's extremely useful to not have to host a chart repository.
Another is the ability to run arbitrary shell hooks locally before and after the chart is released. This allows us to get around the poor handling of secrets in helm.

Thanks for bringing it up!
