### ISSUE TITLE
Autohelm should detect if an environment variable being used is not present

### ISSUE THREAD

**Issue by robscott** [reactiveops/autohelm#32]
One of the great parts of Autohelm is the ability to interpolate env vars. Unfortunately when those env vars are not present, an Autohelm run can cause quite a bit of damage. Any way to prevent that from happening would be great.

**Comment by ejether** [comment]
https://github.com/reactiveops/autohelm/blob/master/autohelm/autohelm.py#L387

Looks like this work has been completed.
