### ISSUE TITLE
`--debug` flag disables `--dry-run` flag

### ISSUE THREAD

**Issue by erkolson** [reactiveops/autohelm#51]
When using both flags together, as in:
```
autohelm plot --dry-run --debug ./course.yaml
```
The `--dry-run` flag does not get passed, which is unexpected.  

When used alone, i.e. `autohelm plot --dry-run ./course.yaml`, the`--debug` flag is passed to helm.  

I would offer a PR but it seems like this behavior is intentional?
https://github.com/reactiveops/autohelm/blob/master/autohelm/autohelm.py#L246-L251

**Comment by sudermanjr** [comment]
We do intentionally imply `--debug` with `--dry-run`.  I would recommend just using `--dry-run`.  

A PR to fix the first behavior would be welcome however, since that seems incorrect to me.  When specifying both flags, you should get both flags.

**Comment by erkolson** [comment]
Here you go:
https://github.com/reactiveops/autohelm/pull/52
